# Replace your ghost 'routes.yaml' with the following
routes:
  /: home # template for homepage `home.hbs`

collections:
  /:
    permalink: /{slug}/
    template: index

  /project/: # a collection called project
    permalink: /project/{slug}/
    template: project # template `project.hbs`
    filter: tag:project # fetch data from a tag      
    data: tag.project # have access to all data & meta data from tag

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/